repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: '^{{cookiecutter\.project_slug}}/'
      - id: end-of-file-fixer
        exclude: '^{{cookiecutter\.project_slug}}/'
      - id: check-yaml
        exclude: '^{{cookiecutter\.project_slug}}/'
      - id: check-json
        exclude: '^{{cookiecutter\.project_slug}}/'
      - id: check-toml
        exclude: '^{{cookiecutter\.project_slug}}/'
