# Configuration file for CLI Coverage Test
# This file provides default configuration values that can be overridden
# by environment variables. See README.md for details.

app:
  name: cli_coverage_test
  version: "0.1.0"
  debug: false

logging:
  level: INFO
  console_level: INFO
  file_level: DEBUG
  file_path: logs/cli_coverage_test.log
  max_file_size: "10MB"
  backup_count: 5

api:
  timeout: 30
  max_retries: 3
  base_url: null  # Set this to your API endpoint

database:
  url: null  # Set this to your database URL (e.g., postgresql://user:pass@host:port/db)
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30

security:
  mask_sensitive_data: true
  allowed_log_fields:
    - timestamp
    - level
    - message
    - module
    - user_id  # Example of allowed ID field

# Add your custom configuration sections here
# custom:
#   feature_flag: true
#   external_service_url: "https://example.com/api"
