version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "your-username"
    assignees:
      - "your-username"

  # Python pip dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    groups:
      # Group development dependencies
      dev-dependencies:
        patterns:
          - "pytest*"
          - "mypy*"
          - "ruff*"
          - "pre-commit*"
          - "types-*"
          - "mkdocs*"
      # Group production dependencies
      prod-dependencies:
        patterns:
          - "pyyaml*"
          - "python-dotenv*"
          - "colorama*"